# Generated by Django 6.0.4 on 2026-04-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debatetopic',
            name='ai_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='opinion',
            name='is_toxic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opinion',
            name='sentiment_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='opinion',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
